version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: memsql
            port: 3306
            user: root
            migrations: true
  memsql:
    image: memsql/quickstart
    ports:
      - "3306:3306"
      - "9001:9000"